config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.
  root 'welcome#home'
  
  
  get "/signup", to: "users#new", as: 'new_user_path'
  get "/login", to: "sessions#new", as: 'login_path'
  post "/login", to: "sessions#create"
  delete '/logout', to: "sessions#destroy", as: 'logout_path'
  get '/logout', to: "sessions#destroy"


  resources :users 

  resources :users, only: [:show] do
    # nested resource for business
    resources :businesses, only: [:show, :new, :index, :create, :edit, :update]
  end

  resources :businesses, only: [:index]
  resources :categories

  #get 'categories/:category_id/businesses', to: 'businesses#index', as: 'categories_business'
  resources :comments
  
  post "/businesses/:id/delete", to: "businesses#destroy"

  get '/auth/google_oauth2/callback', to: "sessions#google_login"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base 
    belongs_to :user, optional: true 
    belongs_to :category, optional: true 
    #validates :category, presence: true
    has_many :comments, through: :user 
    has_one_attached :image





end 

app/models/businesses.rb
class Business < ActiveRecord::Base 
    belongs_to :user 
    belongs_to :category
    has_many :comments



end 

app/models/categories.rb
class Category < ActiveRecord::Base 
    has_many :businesses


end 

app/models/category.rb
class Category < ActiveRecord::Base 
    has_many :businesses
    has_many :users, through: :businesses
    validates :title, presence: true

end 

app/models/comment.rb
class Comment < ActiveRecord::Base 

    belongs_to :user, optional: true  
    belongs_to :businesses, optional: true 

end 

app/models/comments.rb
class Comment < ActiveRecord::Base 

    belongs_to :user 
    belongs_to :businesses

end 

app/models/user.rb
class User < ActiveRecord::Base 

    has_secure_password
    has_many :comments
    has_many :comments, through: :businesses
    has_many :businesses

    validates_presence_of :username
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, confirmation: { case_sensitive: true }

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    #before_action :verified_user
    helper_method :current_user
      

    def /
        
    end 

    def log_in(user)
        session[:user_id] = user.id
    end 

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end 

    def logged_in?
        !current_user.nil?
    end 

    def log_out
        session.delete(:user_id)
        #@current_user = nil
    end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
    #before_action :logged_in?, only: [:show, :edit, :update, :destroy]
    before_action :current_user, only: [:show, :index, :new, :create, :edit]
    protect_from_forgery
    #skip_before_action :verify_authenticity_token

def index 
    if current_user
        @businesses = @current_user.businesses

      else
        @businesses = Business.all
    end
    #byebug
end


def new
    if current_user
        #@user = User.find_by(id: session[:user_id])
        @business = Business.new
    else 
        redirect_to login_path, notice: "User not found"
    end 
    #byebug
    #@business = Business.new
end 

def create
    @business = Business.new(business_params) 
   if @business.save
    current_user.businesses << @business
    #session[:user_id] = @user.id
        redirect_to user_businesses_path
   else 
        redirect_to new_user_business_path
   end 
end 



def show 
    #byebug 
    @business = current_user.businesses.find_by(user_id: params[:id], id: params[:user_id])
        #byebug
        render :show
    #byebug
end 


def edit 
    if !logged_in?
        redirect_to login_path
    end
    @business = current_user.businesses.find_by(user_id: params[:id], id: params[:user_id])
        if @business.title != nil || @business.description != nil 
                render :edit
            else 
                redirect_to new_user_business_path
            end 
         
end 

def update
    business = Business.find_by(id: params[:id])
    business.update(business_params)
    business.save
    redirect_to user_businesses_path
end 

def destroy
    @business = Business.find_by(id: params[:id])
    @business.destroy
    redirect_to user_businesses_path
end

private




def business_params
    params.require(:business).permit(:title, :image, :city, :state, :user_id, :category_id, :description)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def show
    @category = Category.find params[:id]
  end

  def create
    @category = Category.create(category_params)
      if @category.valid?
        redirect_to categories_path
      else
        render :new
      end
  
  end
    
  def edit
    @category = Category.find params[:id]
  end
    
  def update
    @category = Category.find params[:id]
    @category.update(category_params)
    redirect_to categories_path
  end
  
  def destroy
    @category = Category.find params[:id]
    @category.destroy
    redirect_to categories_path
   end
  
    
    private
    
      def category_params
        params.require(:category).permit(:title)
      end
    
end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
      @comments = Comment.all
    end
    
    def new
      @comment = Comment.new
    end
    
    def create
      @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to comments_path(@comment)
      else
        render 'new'
      end
    end
    
    def show
      @comment = Comment.find(params[:id])
    end
    
    private
    
      def comment_params
        params.require(:comment).permit(:body)
      end
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

 #controller for logging in users   

def index
    
end

def new
    user = User.find_by(id: session[:user_id])
    if logged_in?
        redirect_to user_path(user)
    end
end 

def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user_businesses_path(user)
    else 
        flash.now[:danger] = "Invalid email/password. Please try again."
        render :new
    end 
end 



def destroy
    log_out #if logged_in?
    redirect_to '/'
end

def google_login
    user_email = request.env['omniauth.auth']['info']['email']
    user_name = request.env['omniauth.auth']['info']['name']
    @user = User.find_or_create_by(email: user_email) do |user|
        user.username = user_name 
        user.password = SecureRandom.hex
    end 
        log_in @user
        redirect_to businesses_path
    end
    
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit, :update, :destroy]
  protect_from_forgery
  
  #controller for signing up users
  def index 

  end 

  def new 
    @user = User.new 
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to the Forge App!"
        redirect_to login_path
      else 
        render :new 
      end 
    end 

  def show
    if current_user
      #user = User.find(params[:user_id])
      redirect_to user_businesses_path(@current_user)
    else 
      redirect_to "/"
    
      
    end
  end 

  private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 


def home 
   
end 

#def index 
 #if logged_in?
    #@user = current_user
    #@businesses = current_user.businesses
    #render :show
 #else 
    #redirect_to login_path
 #end
#end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end 

    def current_user
        @current_user ||= User.find_by(id: session[user_id])
    end 

    def logged_in?
        !current_user.nil?
    end 

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end 

app/views/businesses/_form.html.erb
<!-- form for creating a new business -->

<%= form_for([@current_user, @business]) do |f| %>
<%= f.label :title, "Name of Business"  %>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :category %>
<%= f.collection_select :category_id, Category.all, :id, :title %>
<br>
<br> 
<%= f.label :image %>
<%= f.file_field :image %>
<br>
<br>
<%= f.label :city %>
<%= f.text_field :city %>
<br>
<br>
<%= f.label :state %>
<%= f.text_field :state %>
<br>
<br>
<%= f.label :description  %>
<%= f.text_field :description %>
<br>
<br>


<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<%= f.submit "Forge Business" %>

<% end %>

app/views/businesses/edit.html.erb
<!-- form for creating a new business -->
<h1>Welcome, <%= current_user.username %> </h1>
<br>
<br>

<%= render "form" %>

app/views/businesses/index.html.erb
<h1>Businesses in South Carolina</h1><br>


<% @businesses.each do |business| %>
<!--<a href="/businesses/<%= business.id %>"style="color: black"><%= business.title %> - <%= business.city %>,<%= business.state %></a>-->
<%= link_to business.title, user_business_path(business, @current_user) %><br>
<% end %><br><br>
<button><h3><%= link_to "Add a New Business", new_user_business_path(@current_user) %></h3></button>

<br><br>

app/views/businesses/new.html.erb
<!-- form for creating a new business -->
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1>Welcome, <%= current_user.username %> </h1>
<br>
<br>

<%= render "form" %>

app/views/businesses/show.html.erb
<h1><%= @business.title %></h1><br>
<%= @business.description %>

<br>

<%= link_to "Add Comment", new_comment_path %><br>
<%= link_to "Edit Business", edit_user_business_path %><br>

app/views/categories/edit.html.erb
<%= form_for(@category, url: category_path(@category)) do |f| %>
    
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
    
    <%= f.submit "Submit" %>
<% end %>

app/views/categories/index.html.erb
<div>
    <%= link_to 'Add new category', new_category_path %>
</div>

<% @categories.each do |category|%>
<%= link_to category.title, category_path(category.id) %>

<% end %>

app/views/categories/new.html.erb
<%= form_with(model: @category, url: categories_path, local: true) do |f| %>
    
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
    <%= f.submit "Submit" %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<br>
<br>

<%= button_to "Edit Category", edit_category_path(@category), method: :get %>
<% if @category.businesses.any? %>
        <span>
            You can't delete because there are businesses associated to this category.
        </span>
            <% else %>
                <%= button_to 'Delete Category', category_path(@category), method: :delete %>
    <% end %>

app/views/comments/index.html.erb
<%= @comments.each do |comment| %>

<%= comment.body %>

<% end %>

app/views/comments/new.html.erb
<h1>New Comment </h1>

<%= form_for @comment do |f| %>

<%= f.label :comment %><br>

<%= f.text_area :body %><br>

<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>Forge - Your MarketPlace</title>
    
	<link href="https://fonts.googleapis.com/css?family=Archivo:500|Open+Sans:300,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Oswald:wght@500&display=swap" rel="stylesheet">
	 <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">-->
  <style>
  * {
    /*list-style: none;*/
    margin: 0;
    padding: 0;
  }
  html, body {
    height: 100%;
    width: 100%;
  }

  body {
	background: url('');
	background-attachment: fixed;
	font-family: 'Archivo', sans-serif;
    font-weight: 300;
    line-height: 18px;
  }

  a {
	text-decoration: none;
	font-family: 'Oswald', sans-serif;
  }

  a:hover {
	  text-decoration: underline;
  }

  li.nav-link a {
	  font-weight: 100;
	  color: #FCBB83;
  }

  a.navbar-brand {
	  color: #9E9E9E;
  }

  .navbar {
    position: fixed;
    top: 0;
    width: 100%;
    margin: 0 auto;
    background-color: #ededed;
    z-index: 9999; /*Keeps content from covering up the navbar*/
  }

  .navbar-header {
  float: left;
  position: absolute;
  padding: 14px 16px;
  padding-left: 120px;
  font-size: x-large;
}

.nav-link {
  padding: 14px 16px;
  display: inline-block;
}

.navbar-nav {
  list-style-type: none;
  float: none;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-60%, -50%);
  
}


.navbar-right {
  float: right;
  list-style-type: none;
  padding-right: 40px;
  
}

.navbar-right a {
  font-family: 'Oswald', sans-serif;
  font-weight: 300;
}

.wrapper {
    -webkit-backdrop-filter: blur(10px); /*Fixes Chrome support for backgrop*/
    backdrop-filter: blur(20px);
    /*-moz-box-shadow: 0 0 10px rgba(0,0,0,.3);
    -webkit-box-shadow: 0 0 10px rgba(0,0,0,.3);*/
    box-shadow: 0 0 10px rgba(0,0,0,.3);
    margin: 200px auto;
    max-width: 960px;
    padding: 3.25%; /* 18px / 800px */
    width: 85%;
    padding-top: 50px;
    padding-bottom: 50px;
    border-radius: 10px;
    text-align: center;
  }

  </style>
  </head>

  <body>
  
  <nav class="navbar">
	<div class="container">
	<div class="navbar-header">
		<a href="/businesses" class="navbar-brand">Forge</a></div>

	<ul class="navbar-nav">
		<li class="nav-link"><a href="#">About</a></li>
		<li class="nav-link"><a href="/categories">Categories</a></li>
      
	</ul>
	<ul class="navbar-right">
		<li class="nav-link"><a href="/signup">Sign Up</a></li>
		<li class="nav-link"><a href="/login">Login</li></a>
    <li class="nav-link"><%= link_to "Log Out", logout_path %></li></a>
	</ul></div>
</nav>
</div>

<div class="wrapper">
        <%= yield %>

  
</div>


<footer class="branding">
<small>&copy; 2020 <strong>Forge</strong></small>
  </footer>
    
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign Up:</h1>
<%= form_for @user do |f| %>

<%= f.label :first_name, "First Name:" %>
<%= f.text_field :first_name %>
<br>

<%= f.label :last_name, "Last Name:" %>
<%= f.text_field :last_name %>
<br>

<%= f.label :username, "Username:" %>
<%= f.text_field :username %>
<br>

<%= f.label :email, "Email:" %>
<%= f.text_field :email %>
<br>

<%= f.label :password, "Password:" %>
<%= f.password_field :password %>
<br>

<%=f.label :password_confirmation, "Confirmation" %>
<%=f.password_field :password_confirmation%>

<br>
<%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h2> This is the show page </h2>
<h3> Welcome, <%= @user.username %>

<%= link_to "Logout", logout_path, method: :post %>

app/views/welcome/home.html.erb
<h1>Welcome to Forge!</h1>
<br>
<button><%= link_to "Sign up", new_user_path_url %></button>
<button><%= link_to "Log In", login_path %></button>
<br>
<%= link_to "Sign-In with Google", '/auth/google_oauth2' %>